language: ruby
rvm:
- 2.5.1
script:
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: "RhXiYV7faY7JwRt16yNgIBuNViSWnjTAD6Gso94p19O9iyuraS2bBxR5vuKyGpdHIgvvEQDs2CVE+d3PHoymePRiRcM2l/ke6lDlTNCA1hae5M00xu+5X/XnEGXDYA/g8PCsblTAr8E8ac6g7THm4AhjeM1bLxRAOgxQ6kdEeeDDbJFy+2QpkIH92DORVrgxBZxtON9PPy1cgEAnideAuTd/xLpvZeGCqSGENtqaPdjuQGwaD7DjaBF9Zi6N7+9AUylhlJD04ntfAnFc5wTXysSResuO7YVtlGJ3uZq04/Y8Y7rDoAUddfN9I3ONwYqk1YM8zIvXnXERuOv3LznTW4I7MZHmVi7N9wIourx2sQ3F/n+CIe42PY6YDwtUnu+QL4OeBz5bpVoCV2wAEUA6XW8K9uZJynA4CoZ3q0bPyd66CcLc0+Rt6HJAA0auIK0LrmjwkWAj2Br88k623PqCOLGXVfWBkf7RHSm41l34yCW0KzUU7YGJ2LUd3G8f0IgsQi0auZUD7RZ3RoeH/XTk6Vaxi5C4bSBnx06guZubGMg3NsfRmJTyZ6k/E9nAiZ/2bdjXTHCFCnqroKMEKob2aupSApWQ9DTHbQnW8NicJ1WZH8ZRCXyIn4lQivY2L7Udv4V5K0Pu5cl7qGhKlKyM5emCVa/x38YGks2B7kTqbrE="
  app: eventjini-task

